version: '2'
services:
  springbootapp:
    image: maliciamrg/springbootmultiapp:latest
    container_name: springBootMultiApp
#    depends_on:
#      - mariadb
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://productdb:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
      - 18080:8080

#  mariadb:
#    image: mariadb:latest
#    container_name: productdb
#    volumes:
#      - /home/docker/volumes/myapp/mysql/:/var/lib/mysql/
#    environment:
#      - MYSQL_ROOT_PASSWORD=1234
#      - MYSQL_DATABASE=mydb
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=1234
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8