spring:
  application:
    name: template-multi-module

application:
  version: '^project.version^'
  ipOutsideDocker: http://192.212.40.10:18080/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: metrics_test_application
    enable:
      all: false
      metrics_test_tag: true

