spring:
  application:
    name: template-multi-module
  datasource:
    url: "jdbc:mysql://192.212.40.10:3306/multi-module"
    username: multi-module-username
    password: multi-module-password

  version: '^project.version^'
  ipOutsideDocker: http://192.212.40.10:18080/

  liquibase:
    change-log: classpath:config/liquibase/master.xml


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: metrics_test_application
    enable:
      all: false
      metrics_test_tag: true

